// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB8RpVixszM1bF70y6T_V_NwMuZfiojjc',
    appId: '1:984210947346:web:45125f591e30a6a52187cb',
    messagingSenderId: '984210947346',
    projectId: 'saman-22a25',
    authDomain: 'aman-22a25.firebaseapp.com',
    databaseURL: 'https://saman-1676975414906-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saman-1676975414906.appspot.com',
    measurementId: 'G-H6D4MWWEWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvEmMj43ZGBETQ9_IyixOw8tpf27nWEBI',
    appId: '1:261797289611:android:efe6cf234844b0d80bbe8e',
    messagingSenderId: '261797289611',
    projectId: 'saman-1676975414906',
    databaseURL: 'https://saman-1676975414906-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saman-1676975414906.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeqEBn4b4bvrBMZXO0LHuvBxb20f1zzNw',
    appId: '1:984210947346:ios:d181a8aceb95b9782187cb',
    messagingSenderId: '984210947346',
    projectId: 'saman-22a25',
    databaseURL: 'https://saman-1676975414906-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saman-22a25.appspot.com',
    androidClientId: '261797289611-trqiee2ub4imt7jgevlk3124rab1gpg3.apps.googleusercontent.com',
    iosClientId: '261797289611-p9bs0p888jfmnsukalttpotkl40uqrq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.saman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxsmUnopvmJXfDyrcCbHNpDg6C_2w0XFs',
    appId: '1:261797289611:ios:16945891c9c67e160bbe8e',
    messagingSenderId: '261797289611',
    projectId: 'saman-1676975414906',
    databaseURL: 'https://saman-1676975414906-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'saman-1676975414906.appspot.com',
    androidClientId: '261797289611-trqiee2ub4imt7jgevlk3124rab1gpg3.apps.googleusercontent.com',
    iosClientId: '261797289611-p9bs0p888jfmnsukalttpotkl40uqrq4.apps.googleusercontent.com',
    iosBundleId: 'com.example.saman',
  );
}
